### ISSUE TITLE
libpcre on Debain Strech for Beagle Bone Black

### ISSUE THREAD

**Issue by MaxClerkwell** [epics-modules/stream#9]
```
/home/debian/Apps/stream/lib/linux-arm/libpcre.so: undefined reference to `pcre_jit_exec'
collect2: error: ld returned 1 exit status
```
Can't make streamDevice on BBB even though configure/RELEASE.Common.linux-arm was added and libpcre.so is already in /usr/lib/arm-linux-gnueabihf/ 

How to disable building PCRE with StreamDevice?

**Comment by MaxClerkwell** [comment]
Switched to tag R2-7-7b failed with 

```
/home/debian/Apps/stream/lib/linux-arm/libpcre.so: undefined reference to `pcre_jit_exec'
collect2: error: ld returned 1 exit status
```

**Comment by MaxClerkwell** [comment]
second try probably failed because of a local $(TOP)/lib/$(T_A)/libpcre.so from first try. Deleted it manually made again and worked.

**Comment by prjemian** [comment]
Looks like you resolved it yourself.  Thanks for the info.
